services:
# ============================================
  # ATTACK MACHINE
  # ============================================
  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali-attacker
    hostname: kali-attacker
    stdin_open: true
    tty: true
    networks:
      - lab_network
    volumes:
      - kali-data:/root
    command: >
      bash -c "
      /var/ossec/bin/wazuh-control start &&
      tail -f /dev/null
      "
    # To access: docker exec -it kali-attacker /bin/bash
  # ============================================
  # VULNERABLE TARGETS
  # ============================================
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa-target
    hostname: dvwa-target
    ports:
      - "8080:80"
    networks:
      - lab_network
  juiceshop:
    image: bkimminich/juice-shop
    container_name: juiceshop-target
    hostname: juiceshop-target
    ports:
      - "3000:3000"
    networks:
      - lab_network
  webgoat:
    image: webgoat/webgoat
    container_name: webgoat-target
    ports:
      - "8081:8080"
      - "9090:9090"
    networks:
      - lab_network
  # ============================================
  # WEB SERVER (for log generation)
  # ============================================
  nginx:
    image: nginx:alpine
    container_name: nginx-webserver
    hostname: nginx-webserver
    ports:
      - "8082:80"
    networks:
      - lab_network
    volumes:
      - nginx-logs:/var/log/nginx
# ============================================
  # WAZUH SIEM
  # ============================================
  wazuh-server:
    platform: linux/amd64
    image: wazuh-siem:latest
    build:
      context: .
      dockerfile: Dockerfile.wazuh
    container_name: wazuh-server
    hostname: wazuh-server
    privileged: true
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
   #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - wazuh-data:/var/ossec
    ports:
      - "127.0.0.1:8443:443"      # Wazuh dashboard
      - "192.168.0.52:1514:1514"     # Agent communication
      - "192.168.0.52:1515:1515"     # Agent enrollment
      - "192.168.0.52:55000:55000"   # Wazuh API
      - "127.0.0.1:9200:9200"     # Indexer (optional)
    networks:
      - lab_network
    command: /sbin/init
    tty: true
    stdin_open: true
# ============================================
# NETWORKS
# ============================================
networks:
  lab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

# ============================================
# VOLUMES
# ============================================
volumes:
  kali-data:
  nginx-logs:
  wazuh-data:
